### ISSUE TITLE
Notes when using keyboard

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/StraboSpot-Mobile#14] opened 2020-01-31 16:43 UTC
Notes save when you tap to close the on-screen keyboard. This means that if you are using an external keyboard (no onscreen keyboard appears), there is no way to save the note. 

Just tapping "back" or outside the note box should save it.

**Comment by sdamaraju** [comment] 2020-06-07 06:13
@nicolasmroberts : Looks like this has been taken care with a save button. Please let me know if we can close this issue.

**Comment by sdamaraju** [comment] 2020-06-15 19:09
@jessicagood can you please see this and let me know if I'm missing anything or if this can be closed immediately.

**Comment by nicolasmroberts** [comment] 2020-06-15 19:11
@sdamaraju yes, this issue is now resolved. go ahead and close it

**Comment by sdamaraju** [comment] 2020-06-15 19:12
Unknown commit id. closing as the issue is resolved as part of other commits.

**Closed by sdamaraju** 2020-06-15 19:12 UTC
