### ISSUE TITLE
Mapbox ID

### ISSUE THREAD

**Issue by andrewkrh** [StraboSpot/StraboSpot-Mobile#406] opened 2022-02-24 21:39 UTC
**Describe the bug**
Currently there is not a way to access the Strabo Profile using the version 1.18.0. I think the user initials are a button because it flashes when pressed, but the button doesn't initiate anything. 

Without access to the profile there is no place to enter the Mapbox ID. This means that custom Mapbox styles are not accessible. "style not found"

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes/No
NA

Open "My StraboSpot" ; No option found

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPad pro 11 inch
 - OS: 15.3.1
 - StraboSpot Version 1.18.0

**Additional context**
A work-around to this problem is opening the project via the web version and accessing the profile settings there. The project can then be downloaded to the device and Mapbox styles become functional.

**Comment by NathanNovak** [comment] 2022-02-28 15:46
@andrewkrh I am unable to reproduce this issue.  I loaded the same version as you but the profile page is loading just fine.  Can you give me more detail that is leading to the problem?
  
https://user-images.githubusercontent.com/35514146/156012765-889a11d3-e468-4c49-928f-11535e23800c.MP4

**Comment by NathanNovak** [comment] 2022-02-28 20:24
@andrewkrh I found the reason for the issue and should have this fixed today. When it is fixed I will post it here with the commit.

**Comment by NathanNovak** [comment] 2022-03-01 20:46
@andrewkrh There is a workaround that you can do.  Go into Strabo 1 and add a profile picture.  I am almost done with the fixes for Strabo 2.

**Comment by andrewkrh** [comment] 2022-03-01 21:07
@NathanNovak Great, thank you! Were you also able to check issues #404 and #407?

**Comment by NathanNovak** [comment] 2022-03-02 15:54
> @NathanNovak Great, thank you! Were you also able to check issues #404 and #407?
Fixed with commit 68935e8b920e23c9f52f1ef10efdfe61864112af. 
I should have things working to close out #404.

**Closed by NathanNovak** 2022-03-02 15:54 UTC
