### ISSUE TITLE
plotting measured linear features without type

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/StraboSpot-Mobile#350] opened 2021-07-12 18:05 UTC
If make a linear measurement but don’t choose a Linear Feature Type the map draws a line arrow symbol that points to the north, even though it should point to the trend direction.

**Comment by jessicagood** [comment] 2022-01-05 21:31
The arrow symbol points in the trend direction for me.  @panamint55 can you recreate this issue?

**Comment by jessicagood** [comment] 2022-01-06 16:08
@panamint55 Unable to reproduce as well. Closing.

**Closed by jessicagood** 2022-01-06 16:08 UTC
