### ISSUE TITLE
Open trace data when a trace is opened

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#229] opened 2021-01-23 19:08 UTC
When you open a trace it does not give any information.  See photo

[image](https://user-images.githubusercontent.com/9283127/105611588-67db9c80-5d73-11eb-906f-6720b1cfe2e0.png)

**Comment by jessicagood** [comment] 2021-02-08 18:38
@panamint55 So if there is a Trace you just want the Overview to start as if `Edit` had already been pressed or do you want to see the Trace data in a different, maybe more compact view, but then still press `Edit` to Edit? @nicolasmroberts

**Comment by jessicagood** [comment] 2021-02-09 15:42
Duplicate of #118

**Comment by jessicagood** [comment] 2021-02-09 18:43
@panamint55 decided having the trace type and more specific type in the Spot header like we have already was actually good enough and quality not that important.

**Closed by jessicagood** 2021-02-09 18:43 UTC
