### ISSUE TITLE
Some problems editing

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot-Mobile#235] opened 2021-01-24 00:26 UTC
There are  some  issues  ediitng a  line or point.  Sometimes changing scale helps.  Not sure where this  comes from.

https://user-images.githubusercontent.com/9283127/105617981-5b256b80-5da8-11eb-8b25-578b1213b6dc.mov

https://user-images.githubusercontent.com/9283127/105617986-65476a00-5da8-11eb-805c-fa69cf618a49.mov

**Comment by sdamaraju** [comment] 2021-01-28 17:25
#216 is the root cause for the second issue (2nd video) mentioned in this bug ticket

**Comment by sdamaraju** [comment] 2021-02-05 22:18
@jessicagood can we close this issue, with the explanation provided on the call.

**Closed** 2021-02-08 18:27 UTC
Labels: bug
